services:
    quartz:
        image: fshrmnsfrnd/quartz
        ports:
            - "8080:8080"
        volumes:
            - "C:/Users/Nico/Nextcloud/Dokumente/Obsidian/Nico:/quartz/content/"
        environment:
            - PAGE_TITLE=Quartz 4